version: '3'

services:
  nodejs:
    container_name: UserHobbiessServer
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
      - 9229:9229
    networks:
      - general-network

  mongo:
    container_name: UsersHobbiesDB
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
      - general-network

networks:
  general-network:
    driver: bridge
